# Example to use multiple servers
# Remember to publish address server names in VIRTUAL_HOST for this server IP
proxy:
   image: jwilder/nginx-proxy
   ports:
     - 80:80
   volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro
   restart: always
   
   
server1:
  image: marcelofmatos/phpnetmap
  environment:
   - VIRTUAL_HOST=server1.example.com
  restart: always
  
  
server2:
  image: marcelofmatos/phpnetmap
  environment:
   - VIRTUAL_HOST=server2.example.com
  restart: always
  
  
server3:
  image: marcelofmatos/phpnetmap
  environment:
   - VIRTUAL_HOST=server3.example.com
  restart: always